sequenceDiagram
    participant Browser
    participant Server
    Note right of Browser: User clicks 'Save'

    Browser->>Server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate Server
    Note left of Server: Server appends the new note to data.json

    Server->>Browser: Redirect to https://studies.cs.helsinki.fi/exampleapp/notes
    deactivate Server

    Note right of Browser: Redirect effectively reloads the page

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate Server
    Server-->>Browser: notes HTML file
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate Server
    Server-->>Browser: main.css file
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate Server
    Server-->>Browser: main.js file
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate Server
    Server-->>Browser: data.json file containing notes
    deactivate Server

    Note right of Browser: Code in main.js creates the HTML list using data.json
